services:
  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - food-service
      - nutrition-service

  food-service:
    build: ./food-service
    ports:
      - "8001:8001"

  nutrition-service:
    build: ./nutrition-service
    ports:
      - "8002:8002"